version: '3.8' # Use a recent Docker Compose version

services:
  web:
    build: .
    ports:
      - "5001:5000" # Map host port 5000 to container port 5000
    depends_on:
      - redis
  redis:
    image: redis:latest # Use the official Redis image
    ports:
      - "6379:6379" # Optional: Expose Redis port if needed for external access